### ISSUE TITLE
go test -v fails with Raspbian 10 (buster) on RPi 4

### ISSUE THREAD

**Issue by wangkuiyi** [wangkuiyi/gotorch#97]
```
pi@raspberrypi:~/go/src/github.com/wangkuiyi/gotorch/cgotorch $ make -f Makefile.rpi
rm -f libtorch
ln -s rpi/libtorch libtorch
clang++ -std=c++14 \
-I .. \
-I libtorch/include \
-I libtorch/include/torch/csrc/api/include \
-L libtorch/lib \
-fPIC \
-shared \
cgotorch.cc \
-o libcgotorch.so -install_name @rpath/libcgotorch.so \
-Wl,-rpath,libtorch/lib \
-Wl,-force_load libtorch/lib/libc10.so \
-lc10 -ltorch -ltorch_cpu \
-D_GLIBCXX_USE_CXX11_ABI=1
clang: warning: argument unused during compilation: '-install_name @rpath/libcgotorch.so' [-Wunused-command-line-argument]
pi@raspberrypi:~/go/src/github.com/wangkuiyi/gotorch/cgotorch $ cd ..
pi@raspberrypi:~/go/src/github.com/wangkuiyi/gotorch $ go test -v
=== RUN   TestPanicMNIST
--- PASS: TestPanicMNIST (0.00s)
=== RUN   TestLogSoftmax
--- PASS: TestLogSoftmax (0.00s)
=== RUN   ExampleBackward
--- FAIL: ExampleBackward (0.00s)
panic: size mismatch, m1: [17179869187 x 0], m2: [4294967300 x 0] at /home/pi/src/pytorch/aten/src/TH/generic/THTensorMath.cpp:4 [recovered]
	panic: size mismatch, m1: [17179869187 x 0], m2: [4294967300 x 0] at /home/pi/src/pytorch/aten/src/TH/generic/THTensorMath.cpp:4

goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0x253de90, 0x0, 0x0, 0x15c6f4, 0x0, 0x28c140, 0x2410848, 0x1)
	/home/pi/usr/go/src/testing/example.go:89 +0x488
testing.runExample.func2(0x78b7046f, 0xbfc4a256, 0x7982f7, 0x0, 0x5020e0, 0x2410818, 0x24100d8, 0x241c400, 0x253de90, 0x253dea8)
	/home/pi/usr/go/src/testing/run_example.go:58 +0xd4
panic(0x28c140, 0x2410848)
	/home/pi/usr/go/src/runtime/panic.go:969 +0x118
github.com/wangkuiyi/gotorch.MustNil(0x2153628)
	/home/pi/go/src/github.com/wangkuiyi/gotorch/tensor.go:59 +0x70
github.com/wangkuiyi/gotorch.MM(0x2410838, 0x2410820, 0x2)
	/home/pi/go/src/github.com/wangkuiyi/gotorch/tensor.go:171 +0x48
github.com/wangkuiyi/gotorch_test.ExampleBackward()
	/home/pi/go/src/github.com/wangkuiyi/gotorch/backward_test.go:13 +0x104
testing.runExample(0x2d0b6c, 0xf, 0x2e64a8, 0x0, 0x0, 0x0, 0x0)
	/home/pi/usr/go/src/testing/run_example.go:62 +0x184
testing.runExamples(0x253df70, 0x4ca840, 0x7, 0x7, 0x101)
	/home/pi/usr/go/src/testing/example.go:44 +0x104
testing.(*M).Run(0x24512c0, 0x0)
	/home/pi/usr/go/src/testing/testing.go:1250 +0x1f8
main.main()
	_testmain.go:62 +0x120
exit status 2
FAIL	github.com/wangkuiyi/gotorch	0.325s
pi@raspberrypi:~/go/src/github.com/wangkuiyi/gotorch $
```

**Comment by wangkuiyi** [comment]
Thanks to the hint from @QiJune : In cgotorch/*.cc, we use int64_t; however, in /*.go, we use int.
