### ISSUE TITLE
ExampleTrainMNIST takes forever on Raspbian 10 32bit

### ISSUE THREAD

**Issue by wangkuiyi** [wangkuiyi/gotorch#99]
After https://github.com/wangkuiyi/gotorch/pull/98, GoTorch builds and runs on Raspbian 10, but the test ExampleTrainMNIST takes forever.

**Comment by wangkuiyi** [comment]
After a long time, it crashed.

```
=== RUN   ExampleTrainMNIST
panic: test timed out after 10m0s

goroutine 15071 [running]:
testing.(*M).startAlarm.func1()
	/home/pi/usr/go/src/testing/testing.go:1509 +0xbc
created by time.goFunc
	/home/pi/usr/go/src/time/sleep.go:168 +0x34

goroutine 1 [syscall, 9 minutes]:
github.com/wangkuiyi/gotorch._Cfunc_Tensor_Backward(0x9f137238)
	_cgo_gotypes.go:461 +0x30
github.com/wangkuiyi/gotorch.Tensor.Backward.func1(0x28106c0)
	/home/pi/go/src/github.com/wangkuiyi/gotorch/tensor.go:158 +0x48
github.com/wangkuiyi/gotorch.Tensor.Backward(0x28106c0)
	/home/pi/go/src/github.com/wangkuiyi/gotorch/tensor.go:158 +0x1c
github.com/wangkuiyi/gotorch_test.ExampleTrainMNIST()
	/home/pi/go/src/github.com/wangkuiyi/gotorch/mnist_test.go:51 +0x1e8
testing.runExample(0x2d17b3, 0x11, 0x2e65f4, 0x0, 0x0, 0x0, 0x0)
	/home/pi/usr/go/src/testing/run_example.go:62 +0x184
testing.runExamples(0x283cf70, 0x4cb840, 0x7, 0x7, 0x101)
	/home/pi/usr/go/src/testing/example.go:44 +0x104
testing.(*M).Run(0x28552c0, 0x0)
	/home/pi/usr/go/src/testing/testing.go:1250 +0x1f8
main.main()
	_testmain.go:62 +0x120

goroutine 200 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0xa22c3fa0, 0x72, 0xffffffff)
	/home/pi/usr/go/src/runtime/netpoll.go:203 +0x44
internal/poll.(*pollDesc).wait(0x28fcc54, 0x72, 0x8001, 0x8000, 0xffffffff)
	/home/pi/usr/go/src/internal/poll/fd_poll_runtime.go:87 +0x30
internal/poll.(*pollDesc).waitRead(...)
	/home/pi/usr/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x28fcc40, 0x2944000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/pi/usr/go/src/internal/poll/fd_unix.go:169 +0x174
os.(*File).read(...)
	/home/pi/usr/go/src/os/file_unix.go:263
os.(*File).Read(0x28106d8, 0x2944000, 0x8000, 0x8000, 0x0, 0x0, 0x28fe0b0)
	/home/pi/usr/go/src/os/file.go:116 +0x5c
io.copyBuffer(0x338598, 0x280e070, 0x3384f0, 0x28106d8, 0x2944000, 0x8000, 0x8000, 0x0, 0x0, 0x0, ...)
	/home/pi/usr/go/src/io/io.go:405 +0xd8
io.Copy(...)
	/home/pi/usr/go/src/io/io.go:364
testing.runExample.func1(0x28106d8, 0x28fe0c0)
	/home/pi/usr/go/src/testing/run_example.go:37 +0x58
created by testing.runExample
	/home/pi/usr/go/src/testing/run_example.go:35 +0x124
exit status 2
FAIL	github.com/wangkuiyi/gotorch	600.406s
```

**Comment by wangkuiyi** [comment]
This issue is fixed. During the period between the noticing the fixing and the filing of this issue, we had merged #96 #98 #101 #102 .

**Comment by QiJune** [comment]
There is a timeout flag when running an unit test.
``` 
-timeout d
            If a test binary runs longer than duration d, panic.
            If d is 0, the timeout is disabled.
            The default is 10 minutes (10m).
```

I guess that it takes more than 10 minutes to run the TrainMNIST example in Raspbian. So it crashes. 

The potential solution is to decrease the epoch number or increase the timeout duration.

**Comment by ljk53** [comment]
I need double check the Raspberry Pi PyTorch build - I probably didn't build with BLAS library properly.

**Comment by wangkuiyi** [comment]
@ljk53 More context for your reference:

I tried to run `ExampleTrainMNIST` using the following command on 32-bit Raspbian.

```
go test -v -run TrainMNIST
```

After adding some debug logs, I see that it's the following line of calling `Tensor.Backward()` that takes forever.

https://github.com/wangkuiyi/gotorch/blob/c63bcd562ee44a6ed8884e02e2b88c63e0d4826b/mnist_test.go#L69

The Go function `Tensor.Backward` calls the Cgo wrapper function `Tensor_Backward`, which calls `at::Tensor->backward`.

**Comment by ljk53** [comment]
This seems to be a deadlock issue:
```
(gdb) info threads
  Id   Target Id                                  Frame
* 1    Thread 0xb2f0a010 (LWP 5679) "gdb_sandbox" 0xb3d9bf44 in __GI___pthread_mutex_lock (mutex=0xd9d6d4) at pthread_mutex_lock.c:80
  2    Thread 0xb2efa1a0 (LWP 5682) "gdb_sandbox" futex_wait_cancelable (private=0, expected=0, futex_word=0xb37af3cc) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0xb26f91a0 (LWP 5683) "gdb_sandbox" futex_wait_cancelable (private=0, expected=0, futex_word=0xb37af44c) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  4    Thread 0xb0ef81a0 (LWP 5684) "gdb_sandbox" futex_wait_cancelable (private=0, expected=0, futex_word=0xb37af4cc) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  5    Thread 0x9e4141a0 (LWP 5685) "gdb_sandbox" runtime.futex () at /usr/lib/go-1.11/src/runtime/sys_linux_arm.s:330
  6    Thread 0x9dc131a0 (LWP 5686) "gdb_sandbox" runtime.futex () at /usr/lib/go-1.11/src/runtime/sys_linux_arm.s:330
  7    Thread 0x9d2f01a0 (LWP 5687) "gdb_sandbox" runtime.futex () at /usr/lib/go-1.11/src/runtime/sys_linux_arm.s:330
  8    Thread 0x9c8f01a0 (LWP 5688) "gdb_sandbox" runtime.futex () at /usr/lib/go-1.11/src/runtime/sys_linux_arm.s:330
  9    Thread 0x9bcf01a0 (LWP 5689) "gdb_sandbox" runtime.futex () at /usr/lib/go-1.11/src/runtime/sys_linux_arm.s:330
  10   Thread 0x8d4a01a0 (LWP 5690) "gdb_sandbox" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  11   Thread 0x8cc9f1a0 (LWP 5691) "gdb_sandbox" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  12   Thread 0x8c49e1a0 (LWP 5692) "gdb_sandbox" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  13   Thread 0x9a3661a0 (LWP 5693) "gdb_sandbox" futex_wait_cancelable (private=0, expected=0, futex_word=0xa11fc8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
```

It's unclear who is holding the lock though:
```
(gdb) bt
#0  __lll_lock_wait (futex=futex@entry=0xd9d6d4, private=0) at lowlevellock.c:46
#1  0xb3d9bf44 in __GI___pthread_mutex_lock (mutex=0xd9d6d4) at pthread_mutex_lock.c:80
#2  0xb434cbb4 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)1>::_M_add_ref_lock() () from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#3  0xb589f4e4 in torch::autograd::generated::TanhBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) () from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#4  0xb5eafdd4 in torch::autograd::Node::operator()(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) () from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#5  0xb5eab308 in torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) () from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#6  0xb5eabc38 in torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) () from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#7  0xb5ea64f8 in torch::autograd::Engine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>) () from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#8  0xb5ea9b18 in torch::autograd::Engine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) ()
   from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#9  0xb5e97ae8 in torch::autograd::run_backward(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool) ()
   from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#10 0xb5e99ed4 in torch::autograd::backward(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::optional<bool>, bool) () from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#11 0xb62a3acc in torch::autograd::VariableType::(anonymous namespace)::backward(at::Tensor const&, at::Tensor const&, c10::optional<bool>, bool) () from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#12 0xb5b71edc in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<void (*)(at::Tensor const&, at::Tensor const&, c10::optional<bool>, bool), void, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, c10::optional<bool>, bool> >, void (at::Tensor const&, at::Tensor const&, c10::optional<bool>, bool)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&, c10::optional<bool>, bool) () from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#13 0xb4afe6d8 in at::Tensor::backward(at::Tensor const&, c10::optional<bool>, bool) const () from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libtorch/lib/libtorch_cpu.so
#14 0xb6f503a0 in Tensor_Backward () from /home/pi/go/src/github.com/wangkuiyi/gotorch/cgotorch/libcgotorch.so
#15 0x00066c74 in runtime.asmcgocall () at /usr/lib/go-1.11/src/runtime/asm_arm.s:617
#16 0x000650b8 in runtime.systemstack () at /usr/lib/go-1.11/src/runtime/asm_arm.s:354
#17 0x00064f28 in runtime.rt0_go () at /usr/lib/go-1.11/src/runtime/asm_arm.s:176
#18 0x00064f20 in runtime.rt0_go () at /usr/lib/go-1.11/src/runtime/asm_arm.s:172
#19 0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) p *mutex
$6 = pthread_mutex_t = {Type = Normal, Status = Acquired, possibly with waiters, Owner ID = Unknown, Robust = No, Shared = No, Protocol = None}
```

Looked at the source code, it's a mutex owned by the backprop graph node: https://codebrowser.bddppq.com/pytorch/pytorch/torch/csrc/autograd/function.h.html#torch::autograd::Node::mutex_

Another interesting observation is that a simple network like "torch.Sum(torch.Tanh(torch.MM(data, W)))" works just fine. As soon as I added more operators to the graph, it started deadlocking...

**Comment by ljk53** [comment]
I suspected it's related to memory corruption, so I added asan flags: "-ggdb -fsanitize=address -fno-omit-frame-pointer -static-libstdc++ -static-libasan -lrt" - this only works with g++ so I also changed the compiler from clang++ to g++.

To my surprise, the problem was gone after switching to g++! We might be hitting some really tricky compatibility problem between gcc/clang...

**Comment by wangkuiyi** [comment]
Followed @ljk53 's solution -- use GCC other than Clang, which is required according to libtorch official document, solved the problem.
